sudo: required
services:
  - docker

before_install:
  - docker build -t dockeryoutube -f Dockerfile.dev .

script:
  - docker run -e CI=true dockeryoutube npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  region: "us-east-1"
  app: "docker-youtube"
  env: "Dockeryoutube-env"
  bucket_name: "elasticbeanstalk-us-east-1-959857001111"
  bucket_path: "docker-youtube"
  on:
    branch: master
